version: '3'
services:
  web:
    build: .
    volumes: 
      - .:/opt/app
    ports: 
      - 4000:4000
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    networks:
      - onboarding-rebase
networks:
  onboarding-rebase:
    name: onboarding_rebase